/** Static alphabet reference data for the Alphabets tool. */

import { ALPHABETS_EXT } from './_alphabets-data-ext.js';

const GOJUON_HIRAGANA = [
    { label: 'a', chars: [{ char: 'あ', roman: 'a' }, { char: 'い', roman: 'i' }, { char: 'う', roman: 'u' }, { char: 'え', roman: 'e' }, { char: 'お', roman: 'o' }] },
    { label: 'ka', chars: [{ char: 'か', roman: 'ka' }, { char: 'き', roman: 'ki' }, { char: 'く', roman: 'ku' }, { char: 'け', roman: 'ke' }, { char: 'こ', roman: 'ko' }] },
    { label: 'sa', chars: [{ char: 'さ', roman: 'sa' }, { char: 'し', roman: 'shi' }, { char: 'す', roman: 'su' }, { char: 'せ', roman: 'se' }, { char: 'そ', roman: 'so' }] },
    { label: 'ta', chars: [{ char: 'た', roman: 'ta' }, { char: 'ち', roman: 'chi' }, { char: 'つ', roman: 'tsu' }, { char: 'て', roman: 'te' }, { char: 'と', roman: 'to' }] },
    { label: 'na', chars: [{ char: 'な', roman: 'na' }, { char: 'に', roman: 'ni' }, { char: 'ぬ', roman: 'nu' }, { char: 'ね', roman: 'ne' }, { char: 'の', roman: 'no' }] },
    { label: 'ha', chars: [{ char: 'は', roman: 'ha' }, { char: 'ひ', roman: 'hi' }, { char: 'ふ', roman: 'fu' }, { char: 'へ', roman: 'he' }, { char: 'ほ', roman: 'ho' }] },
    { label: 'ma', chars: [{ char: 'ま', roman: 'ma' }, { char: 'み', roman: 'mi' }, { char: 'む', roman: 'mu' }, { char: 'め', roman: 'me' }, { char: 'も', roman: 'mo' }] },
    { label: 'ya', chars: [{ char: 'や', roman: 'ya' }, { char: 'ゆ', roman: 'yu' }, { char: 'よ', roman: 'yo' }] },
    { label: 'ra', chars: [{ char: 'ら', roman: 'ra' }, { char: 'り', roman: 'ri' }, { char: 'る', roman: 'ru' }, { char: 'れ', roman: 're' }, { char: 'ろ', roman: 'ro' }] },
    { label: 'wa', chars: [{ char: 'わ', roman: 'wa' }, { char: 'を', roman: 'wo' }, { char: 'ん', roman: 'n' }] },
];

const GOJUON_KATAKANA = [
    { label: 'a', chars: [{ char: 'ア', roman: 'a' }, { char: 'イ', roman: 'i' }, { char: 'ウ', roman: 'u' }, { char: 'エ', roman: 'e' }, { char: 'オ', roman: 'o' }] },
    { label: 'ka', chars: [{ char: 'カ', roman: 'ka' }, { char: 'キ', roman: 'ki' }, { char: 'ク', roman: 'ku' }, { char: 'ケ', roman: 'ke' }, { char: 'コ', roman: 'ko' }] },
    { label: 'sa', chars: [{ char: 'サ', roman: 'sa' }, { char: 'シ', roman: 'shi' }, { char: 'ス', roman: 'su' }, { char: 'セ', roman: 'se' }, { char: 'ソ', roman: 'so' }] },
    { label: 'ta', chars: [{ char: 'タ', roman: 'ta' }, { char: 'チ', roman: 'chi' }, { char: 'ツ', roman: 'tsu' }, { char: 'テ', roman: 'te' }, { char: 'ト', roman: 'to' }] },
    { label: 'na', chars: [{ char: 'ナ', roman: 'na' }, { char: 'ニ', roman: 'ni' }, { char: 'ヌ', roman: 'nu' }, { char: 'ネ', roman: 'ne' }, { char: 'ノ', roman: 'no' }] },
    { label: 'ha', chars: [{ char: 'ハ', roman: 'ha' }, { char: 'ヒ', roman: 'hi' }, { char: 'フ', roman: 'fu' }, { char: 'ヘ', roman: 'he' }, { char: 'ホ', roman: 'ho' }] },
    { label: 'ma', chars: [{ char: 'マ', roman: 'ma' }, { char: 'ミ', roman: 'mi' }, { char: 'ム', roman: 'mu' }, { char: 'メ', roman: 'me' }, { char: 'モ', roman: 'mo' }] },
    { label: 'ya', chars: [{ char: 'ヤ', roman: 'ya' }, { char: 'ユ', roman: 'yu' }, { char: 'ヨ', roman: 'yo' }] },
    { label: 'ra', chars: [{ char: 'ラ', roman: 'ra' }, { char: 'リ', roman: 'ri' }, { char: 'ル', roman: 'ru' }, { char: 'レ', roman: 're' }, { char: 'ロ', roman: 'ro' }] },
    { label: 'wa', chars: [{ char: 'ワ', roman: 'wa' }, { char: 'ヲ', roman: 'wo' }, { char: 'ン', roman: 'n' }] },
];

export const ALPHABETS = [
    {
        id: 'greek',
        title: 'Greek',
        subtitle: '24 letters · uppercase & lowercase',
        fontFamily: "'Segoe UI', 'Arial Unicode MS', sans-serif",
        layout: 'case',
        chars: [
            { charUpper: 'Α', charLower: 'α', roman: 'alpha' }, { charUpper: 'Β', charLower: 'β', roman: 'beta' },
            { charUpper: 'Γ', charLower: 'γ', roman: 'gamma' }, { charUpper: 'Δ', charLower: 'δ', roman: 'delta' },
            { charUpper: 'Ε', charLower: 'ε', roman: 'epsilon' }, { charUpper: 'Ζ', charLower: 'ζ', roman: 'zeta' },
            { charUpper: 'Η', charLower: 'η', roman: 'eta' }, { charUpper: 'Θ', charLower: 'θ', roman: 'theta' },
            { charUpper: 'Ι', charLower: 'ι', roman: 'iota' }, { charUpper: 'Κ', charLower: 'κ', roman: 'kappa' },
            { charUpper: 'Λ', charLower: 'λ', roman: 'lambda' }, { charUpper: 'Μ', charLower: 'μ', roman: 'mu' },
            { charUpper: 'Ν', charLower: 'ν', roman: 'nu' }, { charUpper: 'Ξ', charLower: 'ξ', roman: 'xi' },
            { charUpper: 'Ο', charLower: 'ο', roman: 'omicron' }, { charUpper: 'Π', charLower: 'π', roman: 'pi' },
            { charUpper: 'Ρ', charLower: 'ρ', roman: 'rho' }, { charUpper: 'Σ', charLower: 'σ', roman: 'sigma' },
            { charUpper: 'Τ', charLower: 'τ', roman: 'tau' }, { charUpper: 'Υ', charLower: 'υ', roman: 'upsilon' },
            { charUpper: 'Φ', charLower: 'φ', roman: 'phi' }, { charUpper: 'Χ', charLower: 'χ', roman: 'chi' },
            { charUpper: 'Ψ', charLower: 'ψ', roman: 'psi' }, { charUpper: 'Ω', charLower: 'ω', roman: 'omega' },
        ],
    },
    {
        id: 'hiragana',
        title: 'Hiragana',
        subtitle: '46 basic kana',
        fontFamily: "'Yu Gothic', 'Hiragino Sans', 'Segoe UI', sans-serif",
        layout: 'kana',
        rows: GOJUON_HIRAGANA,
    },
    {
        id: 'katakana',
        title: 'Katakana',
        subtitle: '46 basic kana',
        fontFamily: "'Yu Gothic', 'Hiragino Sans', 'Segoe UI', sans-serif",
        layout: 'kana',
        rows: GOJUON_KATAKANA,
    },
    {
        id: 'korean',
        title: 'Korean',
        subtitle: 'Hangul jamo · consonants & vowels',
        fontFamily: "'Malgun Gothic', 'Apple SD Gothic Neo', 'Segoe UI', sans-serif",
        layout: 'kana',
        rows: [
            { label: 'cons', chars: [
                { char: 'ㄱ', roman: 'g/k' }, { char: 'ㄴ', roman: 'n' }, { char: 'ㄷ', roman: 'd/t' },
                { char: 'ㄹ', roman: 'r/l' }, { char: 'ㅁ', roman: 'm' }, { char: 'ㅂ', roman: 'b/p' },
                { char: 'ㅅ', roman: 's' }, { char: 'ㅇ', roman: 'ng' }, { char: 'ㅈ', roman: 'j' },
                { char: 'ㅊ', roman: 'ch' }, { char: 'ㅋ', roman: 'k' }, { char: 'ㅌ', roman: 't' },
                { char: 'ㅍ', roman: 'p' }, { char: 'ㅎ', roman: 'h' },
            ] },
            { label: 'dbl', chars: [
                { char: 'ㄲ', roman: 'kk' }, { char: 'ㄸ', roman: 'tt' }, { char: 'ㅃ', roman: 'pp' },
                { char: 'ㅆ', roman: 'ss' }, { char: 'ㅉ', roman: 'jj' },
            ] },
            { label: 'vow', chars: [
                { char: 'ㅏ', roman: 'a' }, { char: 'ㅑ', roman: 'ya' }, { char: 'ㅓ', roman: 'eo' },
                { char: 'ㅕ', roman: 'yeo' }, { char: 'ㅗ', roman: 'o' }, { char: 'ㅛ', roman: 'yo' },
                { char: 'ㅜ', roman: 'u' }, { char: 'ㅠ', roman: 'yu' }, { char: 'ㅡ', roman: 'eu' },
                { char: 'ㅣ', roman: 'i' },
            ] },
            { label: 'dip', chars: [
                { char: 'ㅐ', roman: 'ae' }, { char: 'ㅒ', roman: 'yae' }, { char: 'ㅔ', roman: 'e' },
                { char: 'ㅖ', roman: 'ye' }, { char: 'ㅘ', roman: 'wa' }, { char: 'ㅙ', roman: 'wae' },
                { char: 'ㅚ', roman: 'oe' }, { char: 'ㅝ', roman: 'wo' }, { char: 'ㅞ', roman: 'we' },
                { char: 'ㅟ', roman: 'wi' }, { char: 'ㅢ', roman: 'ui' },
            ] },
        ],
    },
    {
        id: 'chinese',
        title: 'Chinese',
        subtitle: '100 most common characters (Simplified)',
        fontFamily: "'Microsoft YaHei', 'PingFang SC', 'Segoe UI', sans-serif",
        layout: 'grid',
        chars: [
            { char: '的', roman: 'de', gloss: 'possessive particle' },
            { char: '一', roman: 'yī', gloss: 'one' },
            { char: '是', roman: 'shì', gloss: 'to be' },
            { char: '不', roman: 'bù', gloss: 'not' },
            { char: '了', roman: 'le', gloss: 'completed action' },
            { char: '人', roman: 'rén', gloss: 'person' },
            { char: '我', roman: 'wǒ', gloss: 'I, me' },
            { char: '在', roman: 'zài', gloss: 'at, in' },
            { char: '有', roman: 'yǒu', gloss: 'to have' },
            { char: '他', roman: 'tā', gloss: 'he, him' },
            { char: '这', roman: 'zhè', gloss: 'this' },
            { char: '为', roman: 'wèi', gloss: 'for, because' },
            { char: '之', roman: 'zhī', gloss: 'of, it' },
            { char: '大', roman: 'dà', gloss: 'big' },
            { char: '来', roman: 'lái', gloss: 'to come' },
            { char: '以', roman: 'yǐ', gloss: 'by means of' },
            { char: '个', roman: 'gè', gloss: 'measure word' },
            { char: '中', roman: 'zhōng', gloss: 'middle, China' },
            { char: '上', roman: 'shàng', gloss: 'up, above' },
            { char: '们', roman: 'men', gloss: 'plural marker' },
            { char: '到', roman: 'dào', gloss: 'to arrive' },
            { char: '说', roman: 'shuō', gloss: 'to say' },
            { char: '国', roman: 'guó', gloss: 'country' },
            { char: '和', roman: 'hé', gloss: 'and, peace' },
            { char: '地', roman: 'dì', gloss: 'earth, ground' },
            { char: '也', roman: 'yě', gloss: 'also' },
            { char: '子', roman: 'zǐ', gloss: 'child, seed' },
            { char: '时', roman: 'shí', gloss: 'time' },
            { char: '道', roman: 'dào', gloss: 'way, path' },
            { char: '出', roman: 'chū', gloss: 'to go out' },
            { char: '而', roman: 'ér', gloss: 'and, but' },
            { char: '要', roman: 'yào', gloss: 'to want' },
            { char: '于', roman: 'yú', gloss: 'at, in' },
            { char: '就', roman: 'jiù', gloss: 'then, just' },
            { char: '可', roman: 'kě', gloss: 'can, may' },
            { char: '会', roman: 'huì', gloss: 'can, meeting' },
            { char: '学', roman: 'xué', gloss: 'to study' },
            { char: '对', roman: 'duì', gloss: 'correct, toward' },
            { char: '生', roman: 'shēng', gloss: 'life, birth' },
            { char: '能', roman: 'néng', gloss: 'can, ability' },
            { char: '自', roman: 'zì', gloss: 'self' },
            { char: '着', roman: 'zhe', gloss: 'aspect particle' },
            { char: '后', roman: 'hòu', gloss: 'after, behind' },
            { char: '事', roman: 'shì', gloss: 'matter, affair' },
            { char: '多', roman: 'duō', gloss: 'many' },
            { char: '然', roman: 'rán', gloss: 'so, correct' },
            { char: '家', roman: 'jiā', gloss: 'home, family' },
            { char: '想', roman: 'xiǎng', gloss: 'to think' },
            { char: '天', roman: 'tiān', gloss: 'sky, day' },
            { char: '年', roman: 'nián', gloss: 'year' },
            { char: '得', roman: 'dé', gloss: 'to get' },
            { char: '小', roman: 'xiǎo', gloss: 'small' },
            { char: '把', roman: 'bǎ', gloss: 'handle, particle' },
            { char: '还', roman: 'hái', gloss: 'still, return' },
            { char: '心', roman: 'xīn', gloss: 'heart' },
            { char: '成', roman: 'chéng', gloss: 'to become' },
            { char: '所', roman: 'suǒ', gloss: 'place' },
            { char: '下', roman: 'xià', gloss: 'down, below' },
            { char: '知', roman: 'zhī', gloss: 'to know' },
            { char: '看', roman: 'kàn', gloss: 'to look' },
            { char: '手', roman: 'shǒu', gloss: 'hand' },
            { char: '方', roman: 'fāng', gloss: 'square, direction' },
            { char: '见', roman: 'jiàn', gloss: 'to see' },
            { char: '开', roman: 'kāi', gloss: 'to open' },
            { char: '用', roman: 'yòng', gloss: 'to use' },
            { char: '分', roman: 'fēn', gloss: 'to divide' },
            { char: '明', roman: 'míng', gloss: 'bright' },
            { char: '行', roman: 'xíng', gloss: 'to walk, OK' },
            { char: '面', roman: 'miàn', gloss: 'face, side' },
            { char: '前', roman: 'qián', gloss: 'front, before' },
            { char: '头', roman: 'tóu', gloss: 'head' },
            { char: '经', roman: 'jīng', gloss: 'classic, pass' },
            { char: '长', roman: 'cháng', gloss: 'long' },
            { char: '水', roman: 'shuǐ', gloss: 'water' },
            { char: '去', roman: 'qù', gloss: 'to go' },
            { char: '法', roman: 'fǎ', gloss: 'law, method' },
            { char: '高', roman: 'gāo', gloss: 'tall, high' },
            { char: '起', roman: 'qǐ', gloss: 'to rise' },
            { char: '两', roman: 'liǎng', gloss: 'two' },
            { char: '三', roman: 'sān', gloss: 'three' },
            { char: '十', roman: 'shí', gloss: 'ten' },
            { char: '二', roman: 'èr', gloss: 'two' },
            { char: '无', roman: 'wú', gloss: 'without' },
            { char: '同', roman: 'tóng', gloss: 'same' },
            { char: '现', roman: 'xiàn', gloss: 'now, appear' },
            { char: '当', roman: 'dāng', gloss: 'when, ought' },
            { char: '没', roman: 'méi', gloss: 'not have' },
            { char: '动', roman: 'dòng', gloss: 'to move' },
            { char: '进', roman: 'jìn', gloss: 'to enter' },
            { char: '好', roman: 'hǎo', gloss: 'good' },
            { char: '些', roman: 'xiē', gloss: 'some' },
            { char: '主', roman: 'zhǔ', gloss: 'main, lord' },
            { char: '样', roman: 'yàng', gloss: 'appearance' },
            { char: '定', roman: 'dìng', gloss: 'to fix' },
            { char: '做', roman: 'zuò', gloss: 'to do, make' },
            { char: '作', roman: 'zuò', gloss: 'to do, work' },
            { char: '里', roman: 'lǐ', gloss: 'inside' },
            { char: '新', roman: 'xīn', gloss: 'new' },
            { char: '问', roman: 'wèn', gloss: 'to ask' },
            { char: '最', roman: 'zuì', gloss: 'most' },
        ],
    },
    {
        id: 'hindi',
        title: 'Hindi',
        subtitle: 'Devanagari vowels and consonants',
        fontFamily: "'Nirmala UI', 'Mangal', 'Segoe UI', sans-serif",
        layout: 'grid',
        chars: [
            { char: 'अ', roman: 'a' }, { char: 'आ', roman: 'ā' }, { char: 'इ', roman: 'i' }, { char: 'ई', roman: 'ī' },
            { char: 'उ', roman: 'u' }, { char: 'ऊ', roman: 'ū' }, { char: 'ए', roman: 'e' }, { char: 'ऐ', roman: 'ai' },
            { char: 'ओ', roman: 'o' }, { char: 'औ', roman: 'au' },
            { char: 'क', roman: 'ka' }, { char: 'ख', roman: 'kha' }, { char: 'ग', roman: 'ga' }, { char: 'घ', roman: 'gha' }, { char: 'ङ', roman: 'ṅa' },
            { char: 'च', roman: 'cha' }, { char: 'छ', roman: 'chha' }, { char: 'ज', roman: 'ja' }, { char: 'झ', roman: 'jha' }, { char: 'ञ', roman: 'ña' },
            { char: 'ट', roman: 'ṭa' }, { char: 'ठ', roman: 'ṭha' }, { char: 'ड', roman: 'ḍa' }, { char: 'ढ', roman: 'ḍha' }, { char: 'ण', roman: 'ṇa' },
            { char: 'त', roman: 'ta' }, { char: 'थ', roman: 'tha' }, { char: 'द', roman: 'da' }, { char: 'ध', roman: 'dha' }, { char: 'न', roman: 'na' },
            { char: 'प', roman: 'pa' }, { char: 'फ', roman: 'pha' }, { char: 'ब', roman: 'ba' }, { char: 'भ', roman: 'bha' }, { char: 'म', roman: 'ma' },
            { char: 'य', roman: 'ya' }, { char: 'र', roman: 'ra' }, { char: 'ल', roman: 'la' }, { char: 'व', roman: 'va' },
            { char: 'श', roman: 'śa' }, { char: 'ष', roman: 'ṣa' }, { char: 'स', roman: 'sa' }, { char: 'ह', roman: 'ha' },
        ],
    },
    {
        id: 'arabic',
        title: 'Arabic',
        subtitle: '28 letters · isolated, initial, medial & final forms',
        fontFamily: "'Segoe UI', 'Traditional Arabic', 'Noto Naskh Arabic', sans-serif",
        layout: 'arabic',
        letters: [
            { roman: 'alif', isolated: 'ا', initial: 'ا', medial: 'ـا', final: 'ـا' },
            { roman: 'bā', isolated: 'ب', initial: 'بـ', medial: 'ـبـ', final: 'ـب' },
            { roman: 'tā', isolated: 'ت', initial: 'تـ', medial: 'ـتـ', final: 'ـت' },
            { roman: 'thā', isolated: 'ث', initial: 'ثـ', medial: 'ـثـ', final: 'ـث' },
            { roman: 'jīm', isolated: 'ج', initial: 'جـ', medial: 'ـجـ', final: 'ـج' },
            { roman: 'ḥā', isolated: 'ح', initial: 'حـ', medial: 'ـحـ', final: 'ـح' },
            { roman: 'khā', isolated: 'خ', initial: 'خـ', medial: 'ـخـ', final: 'ـخ' },
            { roman: 'dāl', isolated: 'د', initial: null, medial: null, final: 'ـد' },
            { roman: 'dhāl', isolated: 'ذ', initial: null, medial: null, final: 'ـذ' },
            { roman: 'rā', isolated: 'ر', initial: null, medial: null, final: 'ـر' },
            { roman: 'zāy', isolated: 'ز', initial: null, medial: null, final: 'ـز' },
            { roman: 'sīn', isolated: 'س', initial: 'سـ', medial: 'ـسـ', final: 'ـس' },
            { roman: 'shīn', isolated: 'ش', initial: 'شـ', medial: 'ـشـ', final: 'ـش' },
            { roman: 'ṣād', isolated: 'ص', initial: 'صـ', medial: 'ـصـ', final: 'ـص' },
            { roman: 'ḍād', isolated: 'ض', initial: 'ضـ', medial: 'ـضـ', final: 'ـض' },
            { roman: 'ṭā', isolated: 'ط', initial: 'طـ', medial: 'ـطـ', final: 'ـط' },
            { roman: 'ẓā', isolated: 'ظ', initial: 'ظـ', medial: 'ـظـ', final: 'ـظ' },
            { roman: 'ʿayn', isolated: 'ع', initial: 'عـ', medial: 'ـعـ', final: 'ـع' },
            { roman: 'ghayn', isolated: 'غ', initial: 'غـ', medial: 'ـغـ', final: 'ـغ' },
            { roman: 'fā', isolated: 'ف', initial: 'فـ', medial: 'ـفـ', final: 'ـف' },
            { roman: 'qāf', isolated: 'ق', initial: 'قـ', medial: 'ـقـ', final: 'ـق' },
            { roman: 'kāf', isolated: 'ك', initial: 'كـ', medial: 'ـكـ', final: 'ـك' },
            { roman: 'lām', isolated: 'ل', initial: 'لـ', medial: 'ـلـ', final: 'ـل' },
            { roman: 'mīm', isolated: 'م', initial: 'مـ', medial: 'ـمـ', final: 'ـم' },
            { roman: 'nūn', isolated: 'ن', initial: 'نـ', medial: 'ـنـ', final: 'ـن' },
            { roman: 'hā', isolated: 'ه', initial: 'هـ', medial: 'ـهـ', final: 'ـه' },
            { roman: 'wāw', isolated: 'و', initial: 'و', medial: 'ـو', final: 'ـو' },
            { roman: 'yā', isolated: 'ي', initial: 'يـ', medial: 'ـيـ', final: 'ـي' },
        ],
    },
    {
        id: 'hebrew',
        title: 'Hebrew',
        subtitle: '22 letters · 5 final forms (sofit) at word end',
        fontFamily: "'Segoe UI', 'David', 'Arial Hebrew', sans-serif",
        layout: 'hebrew',
        chars: [
            { char: 'א', roman: 'alef' }, { char: 'ב', roman: 'bet' }, { char: 'ג', roman: 'gimel' }, { char: 'ד', roman: 'dalet' },
            { char: 'ה', roman: 'he' }, { char: 'ו', roman: 'vav' }, { char: 'ז', roman: 'zayin' }, { char: 'ח', roman: 'het' },
            { char: 'ט', roman: 'tet' }, { char: 'י', roman: 'yod' },
            { char: 'כ', roman: 'kaf', charFinal: 'ך' }, { char: 'ל', roman: 'lamed' },
            { char: 'מ', roman: 'mem', charFinal: 'ם' }, { char: 'נ', roman: 'nun', charFinal: 'ן' },
            { char: 'ס', roman: 'samekh' }, { char: 'ע', roman: 'ayin' },
            { char: 'פ', roman: 'pe', charFinal: 'ף' }, { char: 'צ', roman: 'tsadi', charFinal: 'ץ' },
            { char: 'ק', roman: 'qof' }, { char: 'ר', roman: 'resh' },
            { char: 'ש', roman: 'shin' }, { char: 'ת', roman: 'tav' },
        ],
    },
    {
        id: 'cyrillic',
        title: 'Cyrillic',
        subtitle: 'Russian, Ukrainian & Belarusian',
        fontFamily: "'Segoe UI', 'Arial', sans-serif",
        layout: 'grid',
        chars: [
            { char: 'А', roman: 'a' }, { char: 'Б', roman: 'b' }, { char: 'В', roman: 'v' }, { char: 'Г', roman: 'g' },
            { char: 'Д', roman: 'd' }, { char: 'Е', roman: 'ye' }, { char: 'Ё', roman: 'yo' }, { char: 'Ж', roman: 'zh' },
            { char: 'З', roman: 'z' }, { char: 'И', roman: 'i' }, { char: 'Й', roman: 'y' }, { char: 'К', roman: 'k' },
            { char: 'Л', roman: 'l' }, { char: 'М', roman: 'm' }, { char: 'Н', roman: 'n' }, { char: 'О', roman: 'o' },
            { char: 'П', roman: 'p' }, { char: 'Р', roman: 'r' }, { char: 'С', roman: 's' }, { char: 'Т', roman: 't' },
            { char: 'У', roman: 'u' }, { char: 'Ф', roman: 'f' }, { char: 'Х', roman: 'kh' }, { char: 'Ц', roman: 'ts' },
            { char: 'Ч', roman: 'ch' }, { char: 'Ш', roman: 'sh' }, { char: 'Щ', roman: 'shch' }, { char: 'Ъ', roman: 'hard sign' },
            { char: 'Ы', roman: 'y' }, { char: 'Ь', roman: 'soft sign' }, { char: 'Э', roman: 'e' }, { char: 'Ю', roman: 'yu' },
            { char: 'Я', roman: 'ya' },
            { char: 'І', roman: 'i', gloss: 'Ukrainian' }, { char: 'Ї', roman: 'yi', gloss: 'Ukrainian' },
            { char: 'Є', roman: 'ye', gloss: 'Ukrainian' }, { char: 'Ґ', roman: 'g', gloss: 'Ukrainian' },
            { char: 'Ў', roman: 'u', gloss: 'Belarusian' },
        ],
    },
    ...ALPHABETS_EXT,
];
