/**
 * Auto-generated by scripts/build-tools-list.ps1 - do not edit by hand.
 * Rebuild after changing @tool metadata in js/tools/*.js
 */
export const TOOLS_REGISTRY = [
    {
        "id":  "alphabets",
        "label":  "Alphabets",
        "order":  100,
        "wide":  false,
        "mountClass":  ""
    },
    {
        "id":  "calculator",
        "label":  "Calculator",
        "order":  100,
        "wide":  false,
        "mountClass":  ""
    },
    {
        "id":  "calendar",
        "label":  "Calendar",
        "order":  100,
        "wide":  false,
        "mountClass":  ""
    },
    {
        "id":  "converter",
        "label":  "Converter",
        "order":  100,
        "wide":  false,
        "mountClass":  ""
    },
    {
        "id":  "cosmos",
        "label":  "Cosmos",
        "order":  100,
        "wide":  false,
        "mountClass":  ""
    },
    {
        "id":  "globe",
        "label":  "Globe",
        "order":  100,
        "wide":  false,
        "mountClass":  ""
    },
    {
        "id":  "globe-tz",
        "label":  "Globe Tz",
        "order":  100,
        "wide":  false,
        "mountClass":  ""
    },
    {
        "id":  "map",
        "label":  "Map",
        "order":  100,
        "wide":  false,
        "mountClass":  ""
    },
    {
        "id":  "timezone",
        "label":  "Timezone",
        "order":  100,
        "wide":  false,
        "mountClass":  ""
    }
];
