# Scans js/tools/*.js and writes tools registry (no Node required).
# Run: powershell -NoProfile -ExecutionPolicy Bypass -File scripts/build-tools-list.ps1

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'lib\ArchitectureMapCommon.ps1')

$Root = Get-RepoRoot

function Write-ToolOutputs {
    param([object[]]$Tools, [string]$OutJson, [string]$OutJs)

    $outJsonDir = Split-Path -Parent $OutJson
    $outJsDir = Split-Path -Parent $OutJs
    if (-not (Test-Path -LiteralPath $outJsonDir)) { New-Item -ItemType Directory -Path $outJsonDir -Force | Out-Null }
    if (-not (Test-Path -LiteralPath $outJsDir)) { New-Item -ItemType Directory -Path $outJsDir -Force | Out-Null }

    $json = ($Tools | ConvertTo-Json -Depth 10) + "`n"
    [System.IO.File]::WriteAllText($OutJson, $json, [System.Text.UTF8Encoding]::new($false))

    $registryJson = ($Tools | ConvertTo-Json -Depth 10)
    $js = @(
        '/**',
        ' * Auto-generated by scripts/build-tools-list.ps1 - do not edit by hand.',
        ' * Rebuild after changing @tool metadata in js/tools/*.js',
        ' */',
        "export const TOOLS_REGISTRY = $registryJson;",
        ''
    ) -join "`n"
    [System.IO.File]::WriteAllText($OutJs, $js, [System.Text.UTF8Encoding]::new($false))
}

$targets = @(
    @{
        ToolsDir = Join-Path $Root 'js\tools'
        OutJson  = Join-Path $Root 'api\tools-list.json'
        OutJs    = Join-Path $Root 'js\tools\registry.js'
    }
)

foreach ($target in $targets) {
    if (-not (Test-Path -LiteralPath $target.ToolsDir)) { continue }
    $tools = Get-ToolsRegistry -ToolsDir $target.ToolsDir
    Write-ToolOutputs -Tools $tools -OutJson $target.OutJson -OutJs $target.OutJs
    $rel = $target.OutJs.Substring($Root.Length).TrimStart('\', '/')
    Write-Host "[build-tools-list] $($tools.Count) tools -> $rel"
}
